/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automation_server_JavaCOMServer */

#ifndef _Included_com_automation_server_JavaCOMServer
#define _Included_com_automation_server_JavaCOMServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automation_server_JavaCOMServer
 * Method:    __initializeCOM
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_automation_server_JavaCOMServer__1_1initializeCOM
  (JNIEnv *, jobject);

/*
 * Class:     com_automation_server_JavaCOMServer
 * Method:    __uninitializeCOM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_automation_server_JavaCOMServer__1_1uninitializeCOM
  (JNIEnv *, jobject);

/*
 * Class:     com_automation_server_JavaCOMServer
 * Method:    __createInstance
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_automation_server_JavaCOMServer__1_1createInstance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_automation_server_JavaCOMServer
 * Method:    __invoke
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_automation_server_JavaCOMServer__1_1invoke
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
