/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCOMWrapper */

#ifndef _Included_JavaCOMWrapper
#define _Included_JavaCOMWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     JavaCOMWrapper
 * Method:    __initializeCOM
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JavaCOMWrapper__1_1initializeCOM
  (JNIEnv *, jobject);

/*
 * Class:     JavaCOMWrapper
 * Method:    __uninitializeCOM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCOMWrapper__1_1uninitializeCOM
  (JNIEnv *, jobject);

/*
 * Class:     JavaCOMWrapper
 * Method:    __createInstance
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JavaCOMWrapper__1_1createInstance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaCOMWrapper
 * Method:    __invoke
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_JavaCOMWrapper__1_1invoke
  (JNIEnv *, jobject, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
